### ISSUE TITLE
Blocks to invasive

### ISSUE THREAD

**Issue by zynexiz** [dvershinin/fds#7]
I just tested it on my server/gateway at home, works very well on blocking entire countries. To well.

It sure do block access from a specific country, but it also block outgoing connections to that country. If I block fx. US, I can not access anything coming from there (DuckDuckGo, GitHub etc). Option to accept RELATED ESTABLISHED connections should be allowed when initialized from "the inside", and only block access from new connections made from the outside.

**Comment by dvershinin** [comment]
This shouldn't be the case, because what `fds` merely does is adding the ipset of a country to the `drop` zone of FirewallD.

The `drop` zone, as [documented here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/security_guide/sec-using_firewalls#sec-Zones):

> drop
> Any incoming network packets are dropped without any notification. Only outgoing network connections are possible.

It operates on *incoming* traffic. There's no blocking of outgoing traffic to begin with.

I'd suspect your test was flawed in some way.

**Comment by zynexiz** [comment]
Not sure how the drop zone handle related connections, have to look into that. It seems that the traffic out works, but the returning data is dropped because of the rules.

**Comment by dvershinin** [comment]
You may be thinking in iptables terms. Even then this seems incorrect to me.

An `ESTABLISHED` or `RELATED` as explained [here ](https://serverfault.com/questions/371316/iptables-difference-between-new-established-and-related-packets) are for when the packets either flow in two ways or marked as related.

When you use GitHub API on your own server, for example, there is no connection back from GitHub servers to the requesting side (your server), so it's a purely outgoing connection. :/
